---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Gemspec/RequiredRubyVersion:
  Exclude:
  - aranha-selenium.gemspec
Layout/LineContinuationLeadingSpace:
  Exclude:
  - lib/aranha/selenium/driver_factory.rb
Layout/LineEndStringConcatenationIndentation:
  Exclude:
  - lib/aranha/selenium/driver_factory.rb
RSpec/BeEq:
  Exclude:
  - spec/lib/aranha/selenium/defaults_spec.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - aranha-selenium.gemspec
  - spec/lib/aranha/selenium/defaults_spec.rb
  - spec/rubocop_check_spec.rb
  - spec/spec_helper.rb
