---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - aranha-selenium.gemspec
  - spec/lib/aranha/selenium/defaults_spec.rb
  - spec/rubocop_check_spec.rb
  - spec/spec_helper.rb
